# Dockerfile for React
FROM node:20

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json /app/
RUN npm install

# Copy project
COPY . /app/

# Expose the port
EXPOSE 3001

# Start the React development server
CMD ["npm", "run","dev"]
