# Generated by Django 5.0.7 on 2024-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
